### ISSUE TITLE
UI Tree & IE9 in IE8 Mode

### ISSUE THREAD

**Issue by phototom** [madcapnmckay/Knockout-UI#2]
First, LOVE your UI Tree.  It's what I was trying to write.

When I run in IE9 in IE8 mode, I'm getting the following errors on the debug console -

SCRIPT5007: Unable to get value of the property 'length': object is null or undefined 
ui-tree.js, line 56 character 20
SCRIPT5007: Unable to get value of the property 'children': object is null or undefined 
ui-tree.js, line 485 character 4

It works fine when in IE9 mode.

Suggestions?

**Comment by madcapnmckay** [comment]
Hi phototom,

I have just checked in some changes. Can you grab the latest code and see if you still have the issue?

Just to note, the add node handler is now required to return a node definition instead of an id. This is the only major change, the rest were minor issues and JsLint suggestions.

Thanks,

Ian
